/* <td class=desc> <p class=title>${data.substring(203, 233)}</p> </td>
<td class=desc> <p class=title>${data.substring(233, 263)}</p> </td>
<td class=desc> <p class=title>${data.substring(263, 293)}</p> </td>
<td class=desc> <p class=title>${data.substring(293, 308)}</p> </td>
<td class=desc> <p class=title>${data.substring(308, 310)}</p> </td>
<td class=desc> <p class=title>${data.substring(310, 320)}</p> </td>
<td class=desc> <p class=title>${data.substring(320, 322)}</p> </td>
<td class=desc> <p class=title>${data.substring(322, 352)}</p> </td>
<td class=desc> <p class=title>${data.substring(352, 382)}</p> </td>
<td class=desc> <p class=title>${data.substring(382, 412)}</p> </td>
<td class=desc> <p class=title>${data.substring(412, 442)}</p> </td>
<td class=desc> <p class=title>${data.substring(442, 457)}</p> </td>
<td class=desc> <p class=title>${data.substring(457, 459)}</p> </td>
<td class=desc> <p class=title>${data.substring(459, 469)}</p> </td>
<td class=desc> <p class=title>${data.substring(469, 471)}</p> </td>
<td class=desc> <p class=title>${data.substring(471, 476)}</p> </td>
<td class=desc> <p class=title>${data.substring(476, 485)}</p> </td>
<td class=desc> <p class=title>${data.substring(485, 487)}</p> </td>
<td class=desc> <p class=title>${data.substring(487, 537)}</p> </td>
<td class=desc> <p class=title>${data.substring(537, 538)}</p> </td>
<td class=desc> <p class=title>${data.substring(538, 553)}</p> </td>
<td class=desc> <p class=title>${data.substring(553, 554)}</p> </td>
<td class=desc> <p class=title>${data.substring(554, 569)}</p> </td>
<td class=desc> <p class=title>${data.substring(569, 577)}</p> </td>
<td class=desc> <p class=title>${data.substring(577, 581)}</p> </td>
<td class=desc> <p class=title>${data.substring(581, 587)}</p> </td>
<td class=desc> <p class=title>${data.substring(587, 588)}</p> </td>
<td class=desc> <p class=title>${data.substring(588, 591)}</p> </td>
<td class=desc> <p class=title>${data.substring(591, 891)}</p> </td>
<td class=desc> <p class=title>${data.substring(891, 900)}</p> </td>
<td class=desc> <p class=title>${data.substring(900, 903)}</p> </td>
<td class=desc> <p class=title>${data.substring(903, 911)}</p> </td>
<td class=desc> <p class=title>${data.substring(911, 924)}</p> </td>
<td class=desc> <p class=title>${data.substring(924, 938)}</p> </td>
<td class=desc> <p class=title>${data.substring(938, 941)}</p> </td>
<td class=desc> <p class=title>${data.substring(941, 991)}</p> </td>
<td class=desc> <p class=title>${data.substring(992, 1002)}</p> </td>
<td class=desc> <p class=title>${data.substring(1002, 1004)}</p> </td>
<td class=desc> <p class=title>${data.substring(1007, 1047)}</p> </td>
<td class=desc> <p class=title>${data.substring(1047, 1059)}</p> </td>
<td class=desc> <p class=title>${data.substring(1059, 1062)}</p> </td>
<td class=desc> <p class=title>${data.substring(1062, 1102)}</p> </td>
<td class=desc> <p class=title>${data.substring(1102, 1114)}</p> </td>
<td class=desc> <p class=title>${data.substring(1114, 1117)}</p> </td>
<td class=desc> <p class=title>${data.substring(1117, 1157)}</p> </td>
<td class=desc> <p class=title>${data.substring(1157, 1169)}</p> </td>
<td class=desc> <p class=title>${data.substring(1169, 1172)}</p> </td>
<td class=desc> <p class=title>${data.substring(1172, 1212)}</p> </td>
<td class=desc> <p class=title>${data.substring(1212, 1224)}</p> </td>
<td class=desc> <p class=title>${data.substring(1224, 1227)}</p> </td>
<td class=desc> <p class=title>${data.substring(1227, 1267)}</p> </td>
<td class=desc> <p class=title>${data.substring(1267, 1279)}</p> </td>




        Invoiceamount: linea.substring(56, 67),
        Freightamount: linea.substring(67, 78),
        DutyTaxamount: linea.substring(78, 89),
        Handling: linea.substring(89, 100),
        Discount: linea.substring(100, 111),
        CurrencyCode: linea.substring(111, 114),
        ServiceCode: linea.substring(485, 487),
        PaymentTypeCode: linea.substring(537, 538),
        WeightCode: linea.substring(553, 554),
        DTFlag: linea.substring(587, 588),
        Rebillreasoncode: linea.substring(588, 591),
        Rebillreasondescription: linea.substring(591, 891),
        CustomerPreferredWeight: linea.substring(891, 900),
        BundleNumber: linea.substring(903, 911),
        GroundMultiweightShipmentGroupIndictator: linea.substring(911, 924),
        ExchangeRateAirWaybillLevel: linea.substring(924, 938),
        Chargescount: linea.substring(1002, 1004),
        Chargesrecord: linea.substring(1004, 1007),






















*/